### ISSUE TITLE
Create Texting utility

### ISSUE THREAD

**Issue by jesseparent** [BradCassityDev/git-ticketing-system#2]
Create JS file in Utils directory that accepts a phone number to text a message to, as well as the message to send

**Comment by BradCassityDev** [comment]
Twilio package installed and allows for incoming sms messages that trigger a response and also includes the ability to simply send a text via api route. To use this on a local dev environment, simply setup and install NGrok so that you can access your private IP over the public web. This will generate a URL that must be attached to the number via webhook. If anyone needs help. Please let me know. 

Merged with develop.
